name: secretscanner
on: [push, pull_request]

jobs:
  secretscanner:
    name: secretscanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build -t ghcr.io/k-hal/secretscan-sandbox:${{ github.sha }} .
      - name: run secretscanner
        run: |
          docker run --rm --name=deepfence-secretscanner \
            -v $(pwd):/home/deepfence/output -v /var/run/docker.sock:/var/run/docker.sock \
            -v /usr/bin/docker:/usr/bin/docker \
            deepfenceio/secretscanning \
            -image-name ghcr.io/k-hal/secretscan-sandbox:${{ github.sha }}
